---
# collections for mikrotik_security

collections:
  - name: community.routeros
    source: https://galaxy.ansible.com
    version: 2.0.0-a1

  - name: community.general
    source: https://galaxy.ansible.com
    version: 3.7.0
