---
- name: Perform Mikrotik meris vulnerability check
  hosts: all
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: routeros
    remediate: false
    check_type:
      - unauth_users
    authorized_users:
      - test
      - ansible
    tmp_users: []
    new_tmp_users: []
  collections:
    - community.routeros
  roles:
    - mikrotik_security
