---
# tasks file for mikrotik_security

- debug:
    msg: "Will include tasks for {{ item }} security checks"
  loop: "{{ check_type }}"

- name: Include tasks for security checks
  include_tasks: "{{ item }}.yml"
  loop: "{{ check_type }}"
