---
# tasks file for mikrotik_security

- debug:
    msg: "Will include tasks for {{ item }} security checks"
  loop: "{{ check_type }}"

- name: Include tasks for security checks
  include_tasks: "{{ item }}.yml"
  loop: "{{ check_type }}"

- name: Include tasks for report generation and email
  include_tasks: generate_report.yml
  when:
    - generate_report
    - meris_full_assert.failed is defined or unauth_users_assert.failed is defined
