---
# tasks for meris vulnerability check

- name: Meris - Check socks status
  community.routeros.command:
    commands:
      - /ip socks print
  register: meris_socks_check

- name: Meris - Check for Mikrotik.php file
  community.routeros.command:
    commands:
      - >
        :if ([:len [/file find name~".*[Mm]ikrotik\\.php.*"]] >= 1) do={
          :put "possible breach file"
        } else={ :put "notfound breach file"}
  register: meris_file_check

- name: Meris - Check for mikrotik.php scripts
  community.routeros.command:
    commands:
      - >
        :if ([:len [/system script find source~".*[Mm]ikrotik\\.php.*"]] >= 1) do={
          :put "possible breach script"
        } else={ :put "notfound breach script"}
  register: meris_script_check

- name: Meris - Check for mikrotik.php schedules
  community.routeros.command:
    commands:
      - >
        :if ([:len [/system scheduler find on-event~".*[Mm]ikrotik\\.php.*"]] >= 1) do={
          :put "possible breach schedule"
        } else={ :put "notfound breach schedule"}
  register: meris_schedule_check

- name: Meris - Check for unauthorized users
  community.routeros.command:
    commands:
      - >
        :if ([:len [/user find name~".*service.*"]] >= 1) do={
          :put "possible breach user"
        } else={ :put "notfound breach user"}
  register: meris_user_check

- name: Meris - Include remediation tasks if requested
  include_tasks: "meris_remediation.yml"
  when:
    - remediate
    - "'yes' in {{(meris_socks_check.stdout[0]  | regex_search('enabled: ([a-z]{2,3})', '\\1'))}} or 'possible breach file' in {{(meris_file_check.stdout[0] | regex_search('([a-z]{8} breach file)$', '\\1'))}} or 'possible breach script' in {{ (meris_script_check.stdout[0]  | regex_search('([a-z]{8} breach script)$', '\\1')) }} or 'possible breach schedule' in {{ (meris_schedule_check.stdout[0]  | regex_search('([a-z]{8} breach schedule)$', '\\1')) }} or 'possible breach user' in {{ (meris_user_check.stdout[0]  | regex_search('([a-z]{8} breach user)$', '\\1')) }}"

- name: Meris - Include Assertion tasks to verify results
  include_tasks: "meris_assertions.yml"
