---
# tasks for meris vulnerability remediation

- name: Disable socks and set port to 1080
  community.routeros.command:
    commands:
      - /ip socks set enabled=no
      - /ip socks set port=1080
  register: socks_remediation
  when: "'ye' in {{(socks_check.stdout[0]  | regex_search('enabled: ([a-z]{2,3})', '\\1'))}}"

- name: Remove Mikrotik.php files
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/file find name~".*[Mm]ikrotik\\.php.*"] do={
          /file remove $i
        }
  register: file_remediation
  when: "'possible breach file' in {{(file_check.stdout[0] | regex_search('([a-z]{8} breach file)$', '\\1'))}}"

- name: Remove Mikrotik.php scripts
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/system script find source~".*[Mm]ikrotik\\.php.*"] do={
          /system script remove $i
        }
  register: script_remediation
  when: "'possible breach script' in {{ (script_check.stdout[0]  | regex_search('([a-z]{8} breach script)$', '\\1')) }}"

- name: Remove Mikrotik.php schedule
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/system scheduler find on-event~".*[Mm]ikrotik\\.php.*"] do={
          /system scheduler remove $i
        }
  register: schedule_remediation
  when: "'possible breach schedule' in {{ (schedule_check.stdout[0]  | regex_search('([a-z]{8} breach schedule)$', '\\1')) }}"

- name: Remove unauthorized users
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/user find name~".*service.*"] do={
          /user remove $i
        }
  register: user_remediation
  when: "'possible breach user' in {{ (user_check.stdout[0]  | regex_search('([a-z]{8} breach user)$', '\\1')) }}"
