---
# tasks for meris vulnerability check

- name: Check socks status
  community.routeros.command:
    commands:
      - /ip socks print
  register: socks_check

- name: Check for Mikrotik.php file
  community.routeros.command:
    commands:
      #- "/file [ find where name~\".*[Mm]ikrotik\\.php.*\" ]"
      - /file find where name=mikrotik.php
  register: file_check

- debug: var=file_check.stdout_lines

- name: Include remediation tasks if requested
  include_tasks: "{{ check_type }}_remediation.yml"
  when:
    - remediate
    - "socks_check.stdout_lines[0][0] == 'enabled: yes'"

- name: Include Assertion tasks to verify results
  include_tasks: "{{ check_type }}_assertions.yml"
