---
# tasks for meris vulnerability remediation

- name: Meris - Disable socks and set port to 1080
  community.routeros.command:
    commands:
      - /ip socks set enabled=no
      - /ip socks set port=1080
  register: meris_socks_remediation
  when: meris_found.socks | bool

- name: Meris - Remove Mikrotik.php files
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/file find name~".*[Mm]ikrotik\\.php.*"] do={
          /file remove $i
        }
  register: meris_file_remediation
  when: meris_found.file | bool

- name: Meris - Remove Mikrotik.php scripts
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/system script find source~".*[Mm]ikrotik\\.php.*"] do={
          /system script remove $i
        }
  register: meris_script_remediation
  when: meris_found.script | bool

- name: Meris - Remove Mikrotik.php schedule
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/system scheduler find on-event~".*[Mm]ikrotik\\.php.*"] do={
          /system scheduler remove $i
        }
  register: meris_schedule_remediation
  when: meris_found.schedule | bool

- name: Meris - Remove unauthorized users
  community.routeros.command:
    commands:
      - >
        :foreach i in=[/user find name~".*service.*"] do={
          /user remove $i
        }
  register: meris_user_remediation
  when: meris_found.user | bool
