---
# tasks for meris vulnerability check

- name: Meris - Check socks status
  community.routeros.command:
    commands:
      - /ip socks print
  register: meris_socks_check

- name: Meris - Check for Mikrotik.php file
  community.routeros.command:
    commands:
      - >
        :if ([:len [/file find name~".*[Mm]ikrotik\\.php.*"]] >= 1) do={
          :put "possible breach file"
        } else={ :put "notfound breach file"}
  register: meris_file_check

- name: Meris - Check for mikrotik.php scripts
  community.routeros.command:
    commands:
      - >
        :if ([:len [/system script find source~".*[Mm]ikrotik\\.php.*"]] >= 1) do={
          :put "possible breach script"
        } else={ :put "notfound breach script"}
  register: meris_script_check

- name: Meris - Check for mikrotik.php schedules
  community.routeros.command:
    commands:
      - >
        :if ([:len [/system scheduler find on-event~".*[Mm]ikrotik\\.php.*"]] >= 1) do={
          :put "possible breach schedule"
        } else={ :put "notfound breach schedule"}
  register: meris_schedule_check

- name: Meris - Check for unauthorized users
  community.routeros.command:
    commands:
      - >
        :if ([:len [/user find name~".*service.*"]] >= 1) do={
          :put "possible breach user"
        } else={ :put "notfound breach user"}
  register: meris_user_check

- name: Meris - Summarize indicators
  ansible.builtin.set_fact:
    meris_found:
      socks: "{{ meris_socks_check.stdout[0] is search('enabled: +yes') }}"
      file: "{{ meris_file_check.stdout[0] is search('possible breach file$') }}"
      script: "{{ meris_script_check.stdout[0] is search('possible breach script$') }}"
      schedule: "{{ meris_schedule_check.stdout[0] is search('possible breach schedule$') }}"
      user: "{{ meris_user_check.stdout[0] is search('possible breach user$') }}"

- name: Meris - Include remediation tasks if requested
  include_tasks: "meris_remediation.yml"
  when:
    - remediate
    - meris_found.values() | select | list | length > 0

- name: Meris - Include Assertion tasks to verify results
  include_tasks: "meris_assertions.yml"
