---
# tasks for gathering RouterOS management exposure settings

- name: Security baseline - Collect settings
  ansible.builtin.include_tasks: collect.yml
  vars:
    routeros_collect:
      - services
      - firewall_filter
      - socks
      - romon
      - mac_server
      - mac_winbox
      - bandwidth_server
      - cloud
      - dns
      - device_mode

- name: Security baseline - Include assertion tasks to evaluate settings
  ansible.builtin.include_tasks: security_baseline_assertions.yml
