---
# tasks for unauthorized user assertions

- name: Unauth_users - Get list of users
  community.routeros.command:
    commands:
      - /user print
  register: unauth_user_recheck

- name: Unauth_users - Build list of current users
  set_fact:
    new_tmp_users: "{{ new_tmp_users + [ current_line | regex_search('^ *[0-9]{1,2} {1,5}([a-zA-Z0-9]{1,25}).*$', '\\1', multiline=True) ] | flatten }}"
  loop: "{{ unauth_user_recheck.stdout_lines[0] }}"
  loop_control:
    loop_var: current_line
  no_log: true

- name: Unauth_users - Generate list of unauthorized users
  set_fact:
    new_unauthorized_users: "{{ new_tmp_users | difference( authorized_users ) }}"

- name: Unauth_users - Assert that there are no unauthorized user accounts
  assert:
    that: new_unauthorized_users | length == 0
    success_msg: "Congratulations, No unauthorized users found. This is good!"
    fail_msg: "***DANGER*** unauthorized users found, if you have not done this on purpose your system may be compromised."
  register: unauth_user_assert
  ignore_errors: true
